#/usr/bin/env python3

import os
import shutil
import subprocess
from datetime import datetime

# Import Person A's functions
import network_core

NETPLAN_FILE = "/etc/netplan/99-config.yaml"
DEFAULT_RENDERER = "networkd"  # change to "NetworkManager" if needed
IP_FORWARD_CONF = "/etc/sysctl.d/99-ipforward.conf"


def ask_nameservers():
    """
    Ask user for DNS nameservers.

    Returns:
        list of strings, e.g. ['8.8.8.8', '1.1.1.1']
    """
    ns_raw = input(
        "Enter DNS nameservers (space or comma separated, e.g. 8.8.8.8 1.1.1.1), or leave blank for none: "
    ).strip()
    if not ns_raw:
        return []
    tokens = ns_raw.replace(",", " ").split()
    return tokens


def ask_gateway():
    """
    Ask user for default gateway IPv4 address.

    Returns:
        gateway (str)
    """
    while True:
        gw = input("Enter default gateway IPv4 address (e.g. 192.168.1.1): ").strip()
        if "." in gw:  # TODO: optional better validation
            return gw
        else:
            print("Please enter a valid IPv4 address, for example 192.168.1.1.")


def build_netplan_yaml(interface, mode, address_cidr, gateway, nameservers, renderer=DEFAULT_RENDERER):
    """
    Build a netplan YAML string based on user input.

    Args:
        interface (str)
        mode (str): "dhcp" or "static"
        address_cidr (str or None): required if mode == "static"
        gateway (str or None): required if mode == "static"
        nameservers (list of str)
        renderer (str)

    Returns:
        yaml_content (str)
    """
    ns_str = ", ".join(nameservers) if nameservers else ""

    if mode == "dhcp":
        yaml = f"""# This file was generated by assignment2 tool
network:
  version: 2
  renderer: {renderer}
  ethernets:
    {interface}:
      dhcp4: yes"""
        if nameservers:
            yaml += f"""
      nameservers:
        addresses: [{ns_str}]
"""
        else:
            yaml += "\n"
    else:  # static
        yaml = f"""# This file was generated by assignment2 tool
network:
  version: 2
  renderer: {renderer}
  ethernets:
    {interface}:
      dhcp4: no
      addresses:
        - {address_cidr}
      gateway4: {gateway}
      nameservers:
        addresses: [{ns_str}]
"""
    return yaml


def backup_existing_netplan():
    """Backup existing 99-config.yaml if it exists."""
    if os.path.exists(NETPLAN_FILE):
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_path = f"{NETPLAN_FILE}.bak-{timestamp}"
        print(f"Backing up existing {NETPLAN_FILE} to {backup_path}")
        shutil.copy2(NETPLAN_FILE, backup_path)


def write_netplan_file(content):
    """Write new content to 99-config.yaml."""
    print(f"Writing new configuration to {NETPLAN_FILE}...")
    with open(NETPLAN_FILE, "w") as f:
        f.write(content)
    print("File written successfully.")


def apply_netplan():
    """Apply netplan configuration."""
    try:
        print("Applying netplan configuration...")
        subprocess.check_call(["netplan", "apply"])
        print("netplan apply completed.")
    except Exception as e:
        print(f"Could not run 'netplan apply': {e}")
        print("Run 'sudo netplan apply' manually if needed.")


def enable_ip_forwarding():
    """
    Optionally enable IPv4 forwarding if user agrees.

    - Writes /etc/sysctl.d/99-ipforward.conf
    - Runs 'sysctl -p' on that file
    """
    # Check if multiple non-loopback interfaces exist
    if not network_core.has_multiple_non_loopback_interfaces():
        return  # nothing to do

    ans = input(
        "Detected multiple interfaces. Enable IPv4 forwarding (act as router)? (y/n): "
    ).strip().lower()
    if ans != "y":
        return

    conf_content = "net.ipv4.ip_forward=1\n"
    print(f"Writing IP forwarding config to {IP_FORWARD_CONF}")
    try:
        with open(IP_FORWARD_CONF, "w") as f:
            f.write(conf_content)
        print("IP forwarding config written.")
        print("Applying sysctl settings...")
        subprocess.check_call(["sysctl", "-p", IP_FORWARD_CONF])
        print("IPv4 forwarding enabled.")
    except Exception as e:
        print(f"Failed to enable IP forwarding: {e}")


def configure_network():
    """
    High-level function that runs the full network configuration flow.

    Uses functions from:
    - Person A (network_core)
    - Person B (this file)
    """
    print("\n==== Ubuntu Netplan Configuration Helper ====\n")

    # 1) Show current interfaces
    interfaces = network_core.show_current_interfaces()

    # 2) User selects one
    iface = network_core.choose_interface(interfaces)
    print(f"\nYou selected interface: {iface}\n")

    # 3) Ask DHCP or Static
    mode = network_core.ask_dhcp_or_static()

    address_cidr = None
    gateway = None
    nameservers = []

    if mode == "dhcp":
        print("You chose DHCP mode.")
        override_dns = input("Do you want to manually specify DNS (override DHCP)? (y/n): ").strip().lower()
        if override_dns == "y":
            nameservers = ask_nameservers()
    else:
        print("You chose Static mode.")
        current_ip = network_core.get_current_ipv4(iface)
        address_cidr = network_core.ask_ip_address(current_ip)
        nameservers = ask_nameservers()
        gateway = ask_gateway()

    # Build YAML
    yaml_content = build_netplan_yaml(
        interface=iface,
        mode=mode,
        address_cidr=address_cidr,
        gateway=gateway,
        nameservers=nameservers,
        renderer=DEFAULT_RENDERER,
    )

    print("\nGenerated netplan configuration:\n")
    print(yaml_content)

    # Confirm with user
    confirm = input(
        f"Do you want to write this config to {NETPLAN_FILE}? (y/n): "
    ).strip().lower()
    if confirm != "y":
        print("Aborting network configuration without changes.")
        return

    # Backup and write
    backup_existing_netplan()
    write_netplan_file(yaml_content)

    # Apply?
    apply_now = input("Do you want to apply the new configuration now? (y/n): ").strip().lower()
    if apply_now == "y":
        apply_netplan()
    else:
        print("Remember to run 'sudo netplan apply' later to activate the changes.")
